version: 2
updates:
    -   package-ecosystem: github-actions
        directory: "/"
        schedule:
            interval: weekly
        groups:
            github-actions:
                patterns:
                    - "*"
        commit-message:
            prefix: "chore(deps)"
    -   package-ecosystem: npm
        directory: "/docs"
        schedule:
            interval: weekly
        groups:
            npm:
                patterns:
                    - "@docusaurus/*"
                    - "docusaurus*"
        commit-message:
            prefix: "chore(deps)"