# ===============================================
#      __________
#     < homerun! >
#      ----------
#             \   ^__^
#              \  (oo)\_______
#                 \_/\        )\
#                     ||----\ | \
#                     ||     ||      umazing!
#
# ===============================================
#
# Homerun lets you build ephemeral Minecraft servers,
# while retaining a specific number of chunks. It incentivizes
# building bases close to each other, while allowing for near-
# infinite exploration and exploitation of resources.
#
# This is the main configuration file. Here lies where all your
# settings are defined.

# This defines a set of reset rules. A "reset rule" is a specific
# set of conditions that, when met, will cause chunks to be reset.
# The conditions and the reset parameters are both configurable.
# ALL conditions must be met for a reset to occur.
reset_rules:
    -   name: default
        enabled: false
        # Notify users when they're entering this area?
        notify_enter: true
        # Notify users when they're leaving this area?
        notify_exit: true
        # Distance from a chunk bordered at which to show a physical border (shown as blocks). Setting this to 0 or
        # lower will disable the physical border, but players will still be notified when they cross the border if
        # notify_enter and notify_exit are enabled.
        borders:
            # Change the highest block of the unretained chunks when the player is 3 blocks away from a retained chunk
            # border. By default, a redstone block is used for the border, but this can be customized with "block".
            # The block will show up on the highest non-fluid block. If you want a different heightmap, you can set
            # "heightmap" with any of the available heightmaps: https://minecraft.wiki/w/Heightmap
            -   type: highest_block
                distance_chunks: 3
                heightmap: ocean_floor
            # Show particles above the start of unretained chunks when the player is 7 blocks away from a retained
            # chunk border. The particles look like redstone dust by default, but this can be customized with "color".
            -   type: particles
                particle: dust
                data:
                    color: red
                    size: 1.0
                count: 1
                distance_blocks: 7
                height: 1
                pattern: random
        conditions:
            # Run a reset every day at midnight on the server's local time.
            # This is ALWAYS based on the server's local time, regardless of the timezone setting in messages.yml.
            -   cron: "0 0 * * *" # Every day at midnight
        warnings:
            # Show a boss bar 60 seconds before the reset
            -   type: boss_bar
                seconds_before: 60
            # Show a timer on the player list
            -   type: player_list
            # Send chat messages at the specified intervals before the reset
            -   type: chat_message
                intervals: [ 86400, 43200, 21600, 3600, 1800, 600, 300, 60, 30, 10, 5, 4, 3, 2, 1 ]
        parameters:
            -   retained_chunks:
                    # Retain 16 chunks centered on the world spawn point (i.e. 256 blocks across; 8 chunks in each direction).
                    -   from_world_spawn: 16
                    # Retain the entire End center island (the island at 0,0).
                    # This selector only works for the End dimension, and is ignored for other dimensions.
                    -   end_main_island: true
                # The name of the world to reset from. By default, this is the default world
                # (the `level-name` value in the server.properties file). Use this if you want
                # to reset a world back to a specific set of chunks every time, but don't need
                # to keep changes to those chunks after resets.
                #world: world
                # The pattern to follow for newly-created worlds. Pick a pattern which avoids
                # collisions, otherwise worlds may overwrite each other.
                #
                # Some level of templating is allowed. See documentation for details.
                target_world_pattern: world_${timestamp}
                # Whether the default world set in server.properties should be the newly-created
                # world after a reset.
                modify_server_properties: true
                # Whether to automatically restart the server after a reset. This will require a
                # valid restart script under the server's spigot.yml configuration.
                restart: true
                # Behavior for players located outside of retained chunks when a reset occurs.
                # "kill" will kill them, "spawn" will teleport them to their spawn point, "world_spawn" will teleport
                # them to the world spawn point, "ignore" will leave them where they are, "highest" will teleport them
                # to the highest non-air block at their current X/Z coordinates, and "closest"
                # will teleport them to the closest valid location at their current X/Z coordinates.
                outside_player_behavior: "spawn"
                # Behavior for resetting a dimension. This only applies when resetting an
                # overworld dimension; it will be ignored if the source world is a Nether
                # or End dimension.
                # - "normal" will reset the dimension with the same retained chunks as the overworld.
                # - "wipe" will completely wipe the dimension. It will be regenerated based on the seed of the new world.
                # - "copy" will copy the dimension from the source world, retaining the old world's seed.
                # - "rename" will rename the dimension folder from the source world to the new world, retaining all changes.
                nether_behavior: normal
                end_behavior: normal
                # Enable end pillar cleanup due to end pillars being broken and not regenerating properly due to changes in
                # the world seed (which is used to calculate the radius and height of the pillars). Leave this on unless you
                # have a specific reason to disable it. Otherwise, respawning the dragon may form floating pillars and
                # loading in a reset End dimension may spawn stray End Crystals.
                end_pillar_cleanup: true
